import React from "react"
import { PageContainer } from "@/components/layout/PageContainer"
import { EmailHistoryClient } from "@/components/emails/EmailHistoryClient"

export const metadata = {
  title: "Email History — OpsPilot AI",
  description: "View all outgoing, incoming, draft, and failed emails generated by OpsPilot AI agents.",
}

export default function EmailHistoryPage() {
  return (
    <PageContainer
      title="Email History"
      description="All emails dispatched and received by OpsPilot AI — searchable, filterable, with full HTML preview."
      className="!py-0 !max-w-none !px-0 flex flex-col"
    >
      <div style={{ flex: 1, minHeight: 0, overflow: "hidden" }}>
        <EmailHistoryClient />
      </div>
    </PageContainer>
  )
}
